language: ruby
os:
  - osx
  - linux
dist: xenial
osx_image:
  - xcode10.2
  - xcode10.1
  - xcode9.2
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
env:
  global:
    - HOMEBREW_BINTRAY_USER=1480c1
    - HOMEBREW_COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN
    - HOMEBREW_BINTRAY_KEY=$BINTRAY_API_TOKEN
    - HOMEBREW_GIT_NAME=1480c1
before_cache: brew cleanup
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
  - test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv) || { test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv); } || true
  - brew tap 1480c1/SVT-Encoders
  - for formula in $(brew --repository 1480c1/SVT-encoders)/Formula/*.rb; do [ -e "$formula" ] && chmod 644 "$formula" || true; done
script:
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis CI"

  - brew update
  - git -C $(brew --repository homebrew/core) checkout master -f
  - git -C $(brew --repository homebrew/core) reset --hard origin/master
  - brew --env
  - brew config
  - brew readall --aliases 1480c1/svt-encoders
  - brew uses --recursive 1480c1/svt-encoders/svt-av1
  - brew install --only-dependencies --verbose 1480c1/svt-encoders/svt-av1
  - brew install --verbose --build-bottle 1480c1/svt-encoders/svt-av1
  - brew audit 1480c1/svt-encoders/svt-av1 --online
  - brew style 1480c1/svt-encoders/svt-av1
  - brew linkage --test 1480c1/svt-encoders/svt-av1
  - brew install --only-dependencies --include-test 1480c1/svt-encoders/svt-av1
  - brew test 1480c1/svt-encoders/svt-av1 --verbose
  - brew bottle --json 1480c1/svt-encoders/svt-av1

  - |
    if [[ -n "HOMEBREW_BINTRAY_KEY" ]]; then
      brew test-bot SVT-AV1 --ci-upload \
        --bintray-org="1480c1" \
        --git-name="Travis CI" \
        --git-email="travis@travis-ci.com" \
        --root-url="https://dl.bintray.com/1480c1/bottles-svt-encoders"
    fi
  - ls -l
after_success:
  - cd $(brew --repository 1480c1/SVT-encoders)
  - if [[ -n "$GITHUB_OAUTH_TOKEN" && -n "$TRAVIS_REPO_SLUG" ]]; then git push https://${GITHUB_OAUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git; fi

matrix:
  exclude:
    - os: linux
      osx_image: xcode10.1
    - os: linux
      osx_image: xcode9.2