language: ruby
git:
  clone: false
cache:
  bundler: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/bottles
env:
  global:
    - HOMEBREW_BINTRAY_USER=1480c1
    - HOMEBREW_COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN
    - HOMEBREW_BINTRAY_KEY=$BINTRAY_API_TOKEN
    - HOMEBREW_GIT_NAME=1480c1
stages:
  - Mojave
  - High Sierra
  - Sierra
  - Linux
before_cache: brew cleanup
before_install:
  - mkdir -p ~/bottles
  - cd ~/bottles
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
  - test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv) || { test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv); } || true
  - brew tap 1480c1/SVT-Encoders
  - for formula in $(brew --repository 1480c1/SVT-encoders)/Formula/*.rb; do [ -e "$formula" ] && chmod 644 "$formula" || true; done
script:
  - brew update
  - git -C $(brew --repository homebrew/core) checkout master -f
  - git -C $(brew --repository homebrew/core) reset --hard origin/master
  - brew --env
  - brew config
  - brew readall --aliases 1480c1/svt-encoders
  - brew uses --recursive 1480c1/svt-encoders/svt-av1
  - brew install --only-dependencies 1480c1/svt-encoders/svt-av1
  - brew install --build-bottle 1480c1/svt-encoders/svt-av1
  - brew audit 1480c1/svt-encoders/svt-av1 --online
  - brew style 1480c1/svt-encoders/svt-av1
  - brew linkage --test 1480c1/svt-encoders/svt-av1
  - brew install --only-dependencies --include-test 1480c1/svt-encoders/svt-av1
  - brew test 1480c1/svt-encoders/svt-av1
  - brew bottle --no-rebuild --json --root-url="https://dl.bintray.com/1480c1/bottles-svt-encoders" 1480c1/svt-encoders/svt-av1
  - TRAVIS_TAG="BOTTLES"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file:
    - svt-av1--*.bottle.*
matrix:
  include:
    - stage: Mojave
      os: osx
      osx_image: xcode10.2
    - stage: High Sierra
      os: osx
      osx_image: xcode10.1
    - stage: Sierra
      os: osx
      osx_image: xcode9.2
    - stage: Linux
      os: linux
      dist: xenial
      after_success:
        - |
          if [[ -n "HOMEBREW_BINTRAY_KEY" ]]; then
            brew test-bot SVT-AV1 --ci-upload \
              --bintray-org="1480c1" \
              --root-url="https://dl.bintray.com/1480c1/bottles-svt-encoders"
          fi
        - cd $(brew --repository 1480c1/SVT-encoders)
        - git config --global user.email "travis@travis-ci.com"
        - git config --global user.name "Travis CI"
        - git fetch --all
        - git reset origin/master
        #- |
        #  if [[ "$(uname -s)" =  "Darwin" ]]; then
        #    case $(sw_vers -productVersion | cut -d. -f2) in
        #      12) MAC_OS_NAME="Sierra" ;;
        #      13) MAC_OS_NAME="High Sierra" ;;
        #      14) MAC_OS_NAME="Mojave" ;;
        #      *) MAC_OS_NAME="Unknown" ;;
        #    esac
        #    git commit -am "SVT-AV1: Update bottle for $MAC_OS_NAME [skip ci]"
        #  else
        #    git commit -am "SVT-AV1: Update bottle for linux [skip ci]"
        #  fi
        - 'git commit -am "SVT-AV1: Update bottle [skip ci]"'
        - if [[ -n "$GITHUB_OAUTH_TOKEN" && -n "$TRAVIS_REPO_SLUG" ]]; then git push https://${GITHUB_OAUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git; fi
