language: minimal
os: osx
osx_image:
  - xcode10.2
  - xcode10.1
  - xcode9.2
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv); test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv); fi
  - brew tap 1480c1/SVT-Encoders
  - if [[ -f "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders/Formula/svt-av1.rb" ]]; then chmod 644 /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders/Formula/svt-av1.rb; fi
  - brew audit SVT-AV1
  - brew install --build-bottle SVT-AV1
  - brew bottle SVT-AV1
before_deploy: export TRAVIS_TAG="bottle"
deploy: &deploybase
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  draft: true
  file_glob: true
  file: svt-av1--0.5.0.*.bottle.tar.gz
  on:
    repo: 1480c1/homebrew-SVT-encoders
matrix:
  include:
    - stage: Build Linux & Deploy
      os: linux
      dist: xenial
      deploy:
        <<: *deploybase
        draft: false
