language: minimal
os:
  - linux
  - osx
osx_image:
  - xcode10.2
  - xcode10.1
  - xcode9.2
dist: xenial
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
      test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
      echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
    fi
  - brew tap 1480c1/SVT-Encoders
  - brew audit SVT-AV1
  - brew install --build-bottle SVT-AV1
after_script:
  - brew bottle SVT-AV1
matrix:
  exclude:
    - os: linux
      osx_image: xcode10.1
    - os: linux
      osx_image: xcode9.2
