language: ruby
os: osx
osx_image:
  - xcode10.2
  - xcode10.1
  - xcode9.2
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
env:
  - HOMEBREW_BINTRAY_USER=1480c1 HOMEBREW_COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN HOMEBREW_BINTRAY_KEY=$BINTRAY_API_TOKEN
before_cache: brew cleanup
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv); test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv); fi
  - brew tap 1480c1/SVT-Encoders
  - if [[ -f "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders/Formula/*.rb" ]]; then chmod 644 /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders/Formula/*.rb; fi
script:
  - brew install --build-bottle SVT-AV1
  - brew bottle --json SVT-AV1
  - brew test-bot --coverage --bintray-org=1480c1/homebrew-SVT-encoders --git-name=1480c1 --git-email=ccom@randomderp.com --ci-upload
  - ls -l
before_deploy:
  - export TRAVIS_TAG="bottle"
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis CI"
deploy: &deploybase
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  draft: true
  file_glob: true
  file: svt-av1-0.5.0.*.bottle.tar.gz
  on:
    repo: 1480c1/homebrew-SVT-encoders
    branch: master
matrix:
  include:
    - stage: Build Linux & Deploy
      os: linux
      dist: xenial
      deploy:
        <<: *deploybase
        draft: false
