strategy:
  matrix:
    mac10.14:
      imageName: 'macos-10.14'
    mac10.13:
      imageName: 'macOS-10.13'
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:
- bash: |
    set -e
    if [[ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]]; then
      git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
      git checkout pr
    fi
    if [[ "$(uname -s)" != "Darwin" ]]; then
      sudo chown -R $(whoami) /usr/local
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    fi
    test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
    test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    brew update
    #HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders"
    #mkdir -p "$HOMEBREW_TAP_DIR"
    #rm -rf "$HOMEBREW_TAP_DIR"
    #ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  displayName: Setup Brew

- bash: brew test-bot SVT-AV1 --root-url="https://dl.bintray.com/1480c1/bottles-svt-encoders/" --verbose
  displayName: Run brew test-bot

- bash: |
    brew test-bot SVT-AV1 --ci-upload --root-url="https://dl.bintray.com/1480c1/bottles-svt-encoders/" --bintray-org="1480c1" --verbose
    export VERSION_STRING=$(git describe --tag --dirty="" --broken="" --abbrev=0)
    export VERSION_STRING=$(python -c "exec('print(\"$VERSION_STRING\"[1:])')")
    curl -u1480c1:$HOMEBREW_BINTRAY_KEY -H Content-Type:application/json -H Accept:application/json -X POST https://api.bintray.com/content/1480c1/homebrew-SVT-encoders/SVT-AV1/$VERSION_STRING/publish -d "{ \"discard\": \"false\" }"
    ssh-keyscan github.com > ~/.ssh/known_hosts
    git push https://$(HOMEBREW_GITHUB_API_TOKEN)@github.com/1480c1/homebrew-SVT-encoders.git HEAD:master
  displayName: brew test-bot upload
  env:
    HOMEBREW_BINTRAY_USER: 1480c1
    HOMEBREW_GITHUB_API_TOKEN: $(GITHUB_OAUTH_TOKEN)
    HOMEBREW_BINTRAY_KEY: $(BINTRAY_API_TOKEN)
