strategy:
  matrix:
    mac10.14:
      imageName: 'macos-10.14'
    mac10.13:
      imageName: 'macOS-10.13'
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

variables:
  HOMEBREW_BINTRAY_USER: 1480c1
  HOMEBREW_GITHUB_API_TOKEN: $(GITHUB_OAUTH_TOKEN)
  HOMEBREW_BINTRAY_KEY: $(BINTRAY_API_TOKEN)

steps:
- bash: |
    set -e
    if [[ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]]; then
      git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
      git checkout pr
    fi
    if ! [[ "${OSTYPE:0:6}" = "darwin" ]]; then
      sudo chown -R `whoami` /usr/local
      sh -c "`curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh`"
    fi
    test -d ~/.linuxbrew && eval `~/.linuxbrew/bin/brew shellenv` || { test -d /home/linuxbrew/.linuxbrew && eval `/home/linuxbrew/.linuxbrew/bin/brew shellenv`; } || true
  displayName: Setup Brew

- bash: |
    brew tap 1480c1/SVT-encoder
    test -f /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders/Formula/svt-av1.rb && sudo chmod 644 /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders/Formula/svt-av1.rb || true
    test -d ~/.linuxbrew && eval `~/.linuxbrew/bin/brew shellenv` || { test -d /home/linuxbrew/.linuxbrew && eval `/home/linuxbrew/.linuxbrew/bin/brew shellenv`; } || true
    brew update
    git -C $(brew --repository homebrew/core) checkout master -f
    git -C $(brew --repository homebrew/core) reset --hard origin/master
    brew --env
    brew config
    brew readall --aliases 1480c1/svt-encoders
    brew uses --recursive 1480c1/svt-encoders/svt-av1
    brew install --only-dependencies 1480c1/svt-encoders/svt-av1
    brew install --build-bottle 1480c1/svt-encoders/svt-av1
    brew linkage --test 1480c1/svt-encoders/svt-av1
    brew install --only-dependencies --include-test 1480c1/svt-encoders/svt-av1
    brew test 1480c1/svt-encoders/svt-av1
    brew bottle --no-rebuild --json --root-url="https://dl.bintray.com/1480c1/bottles-svt-encoders" 1480c1/svt-encoders/svt-av1
  displayName: Run brew test-bot
