strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac10.14:
      imageName: 'macos-10.14'
    mac10.13:
      imageName: 'macOS-10.13'

pool:
  vmImage: $(imageName)

steps:
- bash: |
    set -e
    if [[ "$(uname -s)" != "Darwin" ]]; then
      sudo chown -R $(whoami) /usr/local
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
      test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    fi
    brew update
    HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/1480c1/homebrew-svt-encoders"
    mkdir -p "$HOMEBREW_TAP_DIR"
    rm -rf "$HOMEBREW_TAP_DIR"
    ln -s "$PWD" "$HOMEBREW_TAP_DIR"
    brew install --build-bottle SVT-AV1
    brew bottle --json SVT-AV1
    brew test-bot
  displayName: Run brew test-bot
